/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'NHNEnt' at '17. 4. 20 오전 11:27' with Gradle 2.14.1
 *
 * @author NHNEnt, @date 17. 4. 20 오전 11:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
