import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'NHNEnt' at '17. 4. 20 오전 11:27' with Gradle 2.14.1
 *
 * @author NHNEnt, @date 17. 4. 20 오전 11:27
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
